// Generated by CoffeeScript 1.7.1
(function() {
  var Api, Weya, append, htmlElems, name, parseIdClass, setAttributes, setEvents, setStyles, svgElems, weya, wrapAppend, _i, _j, _len, _len1, _ref, _ref1;

  svgElems = 'a altGlyph altGlyphDef altGlyphItem animate animateColor animateMotion animateTransform circle clipPath color-profile cursor defs desc ellipse feBlend feColorMatrix feComponentTransfer feComposite feConvolveMatrix feDiffuseLighting feDisplacementMap feDistantLight feFlood feFuncA feFuncB feFuncG feFuncR feGaussianBlur feImage feMerge feMergeNode feMorphology feOffset fePointLight feSpecularLighting feSpotLight feTile feTurbulence filter font font-face font-face-format font-face-name font-face-src font-face-uri foreignObject g glyph glyphRef hkern image line linearGradient marker mask metadata missing-glyph mpath path pattern polygon polyline radialGradient rect script set stop style svg symbol text textPath title tref tspan use view vkern';

  htmlElems = 'a abbr address article aside audio b bdi bdo blockquote body button canvas caption cite code colgroup datalist dd del details dfn div dl dt em fieldset figcaption figure footer form h1 h2 h3 h4 h5 h6 head header hgroup html i iframe ins kbd label legend li main map mark menu meter nav noscript object ol optgroup option output p pre progress q rp rt ruby s samp script section select small span strong style sub summary sup table tbody td textarea tfoot th thead time title tr u ul video';

  weya = {
    elem: null
  };

  Api = {
    document: this.document
  };

  setStyles = function(elem, styles) {
    var k, v, _results;
    _results = [];
    for (k in styles) {
      v = styles[k];
      if (v != null) {
        _results.push(elem.style.setProperty(k, v));
      } else {
        _results.push(elem.style.removeProperty(k));
      }
    }
    return _results;
  };

  setEvents = function(elem, events) {
    var k, v, _results;
    _results = [];
    for (k in events) {
      v = events[k];
      _results.push(elem.addEventListener(k, v, false));
    }
    return _results;
  };

  setAttributes = function(elem, attrs) {
    var k, v, _results;
    _results = [];
    for (k in attrs) {
      v = attrs[k];
      switch (k) {
        case 'style':
          _results.push(setStyles(elem, v));
          break;
        case 'on':
          _results.push(setEvents(elem, v));
          break;
        default:
          if (v != null) {
            _results.push(elem.setAttribute(k, v));
          } else {
            _results.push(elem.removeAttribute(k));
          }
      }
    }
    return _results;
  };

  parseIdClass = function(str) {
    var c, i, res, _i, _len, _ref;
    res = {
      id: null,
      "class": null
    };
    _ref = str.split(".");
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      c = _ref[i];
      if (c.indexOf("#") === 0) {
        res.id = c.substr(1);
      } else if (c !== "") {
        if (res["class"] == null) {
          res["class"] = c;
        } else {
          res["class"] += " " + c;
        }
      }
    }
    return res;
  };

  append = function(ns, name, args) {
    var arg, attrs, c, contentFunction, contentText, elem, i, idClass, pElem, _i, _len;
    idClass = null;
    contentText = null;
    attrs = null;
    contentFunction = null;
    for (i = _i = 0, _len = args.length; _i < _len; i = ++_i) {
      arg = args[i];
      switch (typeof arg) {
        case 'function':
          contentFunction = arg;
          break;
        case 'object':
          attrs = arg;
          break;
        case 'string':
          if (args.length === 1) {
            contentText = arg;
          } else {
            c = arg.charAt(0);
            if (i === 0 && (c === '#' || c === '.')) {
              idClass = arg;
            } else {
              contentText = arg;
            }
          }
      }
    }
    pElem = this._elem;
    if (ns != null) {
      elem = this._elem = Api.document.createElementNS(ns, name);
    } else {
      elem = this._elem = Api.document.createElement(name);
    }
    if (idClass != null) {
      idClass = parseIdClass(idClass);
      if (idClass.id != null) {
        elem.id = idClass.id;
      }
      if (idClass["class"] != null) {
        elem.className = idClass["class"];
      }
    }
    if (attrs != null) {
      setAttributes(elem, attrs);
    }
    if (pElem != null) {
      pElem.appendChild(elem);
    }
    if (contentFunction != null) {
      contentFunction.call(this);
    } else if (contentText != null) {
      elem.textContent = contentText;
    }
    this._elem = pElem;
    return elem;
  };

  wrapAppend = function(ns, name) {
    return function() {
      return append.call(this, ns, name, arguments);
    };
  };

  _ref = svgElems.split(' ');
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    name = _ref[_i];
    weya[name] = wrapAppend("http://www.w3.org/2000/svg", name);
  }

  _ref1 = htmlElems.split(' ');
  for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
    name = _ref1[_j];
    weya[name] = wrapAppend(null, name);
  }

  this.Weya = Weya = function(elem, self, func) {
    var pElem, pSelf, r;
    if ((typeof self) === 'function') {
      func = self;
      self = null;
    }
    pSelf = weya["this"];
    weya["this"] = self;
    pElem = weya._elem;
    weya._elem = elem;
    r = func != null ? func.call(weya) : void 0;
    weya._elem = pElem;
    weya["this"] = pSelf;
    return r;
  };

  Weya.create = function(self, func) {
    return Weya(null, self, func);
  };

}).call(this);
